title: IUS
description: IUS is a yum repository that provides newer versions of select software for RHEL and CentOS.
defaults:
  - scope:
      path: ''
    values:
      layout: default
kramdown:
  smart_quotes: ['apos', 'apos', 'quot', 'quot']
